version: '3.3'
services:
  top-api:
    image: docker.pkg.github.com/kharlamovegor/top-api-demo/top-api-demo:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
